EPI_data<-read.csv(file.choose())
View(EPI_data)
attach(EPI_data)
fix(EPI_data)
EPI<-EPI_data$EPI
tf <- is.na(EPI)
E<-EPI[!tf]
summary(EPI)
fivenum(EPI,na.rm=TRUE)
stem(EPI)
hist(EPI)
hist(EPI,seq(30.,95.,1.0),prob = TRUE)
line(density(EPI,na.rm=TRUE,bw=1.))
rug(EPI)
plot(ecdf(EPI),do.points=FALSE,verticals = TRUE)
par(pty='s')
qqnorm(EPI)
qqline(EPI)
x<-seq(30,95,1)
qqplot(qt(ppoints(250),df=5),x,xlab="Q-Q plot for t dsn")
qqline(x)

# for envhealth
envh <- EPI_data$ENVHEALTH
tf <- is.na(envh)
E<-envh[!tf]
summary(envh)
fivenum(envh,na.rm=TRUE)
stem(envh)
hist(envh)
hist(envh,seq(30.,95.,1.0),prob = TRUE)
line(density(envh,na.rm=TRUE,bw=1.))
rug(envh)
plot(ecdf(envh),do.points=FALSE,verticals = TRUE)
par(pty='s')
qqnorm(envh)
qqline(envh)
x<-seq(30,95,1)
qqplot(qt(ppoints(250),df=5),x,xlab="Q-Q plot for t dsn")
qqline(x)

#for daly
daly <- EPI_data$DALY
tf <- is.na(daly)
E<-daly[!tf]
summary(daly)
fivenum(daly,na.rm=TRUE)
stem(daly)
hist(daly)
hist(daly,seq(30.,95.,1.0),prob = TRUE)
line(density(daly,na.rm=TRUE,bw=1.))
rug(daly)
plot(ecdf(daly),do.points=FALSE,verticals = TRUE)
par(pty='s')
qqnorm(daly)
qqline(daly)
x<-seq(30,95,1)
qqplot(qt(ppoints(250),df=5),x,xlab="Q-Q plot for t dsn")
qqline(x)

boxplot(envh,daly) 
qqplot(envh,daly)
